### ISSUE TITLE
Use `unknown` instead of `any`

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/is-what#12]
## CURRENTLY

We currently use `any` a lot like. Eg.:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3253920/91915561-dd2bcf80-ecf5-11ea-95f4-cf9d14222a0f.png">

This currently makes stuff like this possible without error:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/3253920/91916414-0cdbd700-ecf8-11ea-9189-b4ce9ae7432c.png">

## PROPOSAL

When the user passes an array with "any" we could also convert the outcome to "unknown" instead like so:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/3253920/91916487-385ec180-ecf8-11ea-8b4a-7c258f8624d7.png">

Which will result in throwing errors because the type was converted from `any` to `unknown`:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/3253920/91916510-4b719180-ecf8-11ea-94e4-36165ce91033.png">

As long as the array type is not `any[]` it will keep the array type as is:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/3253920/91917089-ef0f7180-ecf9-11ea-8e38-9dc90f3ec1db.png">

@laquasicinque thoughts?

**Comment by mesqueeb** [comment]
the proposal comes from:
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/3253920/91918036-a1483880-ecfc-11ea-8f5c-8569fbcbdae9.png">

**Comment by casr** [comment]
On a related note, you may wish to define an object like:
```ts
// like in TS library files
Record<keyof any, unknown>

// or verbosely without the any
Record<string | number | symbol, unknown>
```

**Comment by mesqueeb** [comment]
will land in v5
