### ISSUE TITLE
Is function isObjectLike checks the type?

### ISSUE THREAD

**Issue by polemius** [mesqueeb/is-what#15]
From documentation I am not quite understanding what really do `isObjectLike`?

Documentation says _Returns whether the payload is an object like a type passed in < >_

I can see that If I passed not an object then it will return the false:

```
isObjectLike<{a: string}>(true) // false
```

But If I passed some object it will return the true any way:

```
isObjectLike<{a: string}>({b: 3}) // true
```

[Link to TS playgound](https://www.typescriptlang.org/play?target=1#code/GYVwdgxgLglg9mABAcwKZQCoE8AOrEAUOAhlgDZzEAmAXIsWFgJR0DOUATjGMogN4BYAFCJEHdCA5IA8gCMAVqmgA6HBzhQNuVMs0BlTt2TKIxMmSKkK1JstZkYEVAQAcAGkQBaAIxNhAX2EgoVBIWAREGFYAQUY5RWhCEnJKWnpGFkRk6ypI1kQAJSU4DioAHnYuHg8GLAA+fmFRcShJJDRMbUsUm0QAXgHEAHJ4pSghgODQ6HgkKNHoABkYAGtUMoxEVAAPKFQwKnyiiBLyyqMaxjqG7py6Wszs1LzETcERMQkpPNisBahbqk-EJAkJhCcwKw4GQdBRkAR5goxss1mU+MQ2IYeP46gROCBUExgRCoTDlHCEax-ij1ujMVVkDiCHxZHQAMz+IlAA)

**Comment by mesqueeb** [comment]
@polemius yeah, I once long ago used it to make some manual type casting easier.

with the hope to one day improve it to have it actually check the object itself, but soon I realised that that's an extremely complex issue and kind of out of scope :S

**Comment by polemius** [comment]
@mesqueeb I understand now. Thank you for explanation
