### ISSUE TITLE
Consider isInstanceOf() based on string tags?

### ISSUE THREAD

**Issue by jcbhmr** [mesqueeb/is-what#36]
A reasonably popular npm package is https://github.com/lamansky/is-instance-of (1k downloads last week), but it's severely outdated. I think this package would be a great place for such a function? Or maybe there already is one that does what I'm looking for and I couldn't find it?

Example use case:

```js
// Covers ServiceWorkerGlobalScope, DedicatedWorkerGlobalScope,
// plain WorkerGlobalScope from web-worker polyfill, SharedWorkerGlobalScope, etc.
if (isInstanceOf(globalThis, "WorkerGlobalScope")) {
  onmessage = (e) => console.log(e.data);
  doThingInWorker(self);
}
doNormalThing();
```

vs the old way

```js
for (let p = globalThis; p; p = Object.getPrototypeOf(p)) {
  if (Object.prototype.toString.call(p).slice(8, -1) === "WorkerGlobalScope") {
    onmessage = (e) => console.log(e.data);
    doThingInWorker(self);
    break;
  }
}
doNormalThing();
```

**Comment by mesqueeb** [comment]
@jcbhmr since is-what is fully tree-shakable, there's no downside on adding new functions! I feel this also is a great addition! : ) 
PRs welcome
