### ISSUE TITLE
Consider using tsx and node:test?

### ISSUE THREAD

**Issue by jcbhmr** [mesqueeb/is-what#44]
I've recently tried to drop Vite & Vitest from my main TS lib workflow and just use plain `tsc`. This works well for me with [tsx](https://github.com/esbuild-kit/tsx) and the [`node:test` builtin](https://nodejs.org/api/test.html).

```sh
tsc
tsx --test --watch **/*.test.ts
```

**Comment by mesqueeb** [comment]
I kinda like vitest. I have the VSCode extensions. and their UI feature is also nice.
not using vite in this package.
