### ISSUE TITLE
Interested in @tinylibs?

### ISSUE THREAD

**Issue by jcbhmr** [mesqueeb/is-what#49]
I can't speak on @mesqueeb your behalf, but I think that @tinylibs seems to have a pretty similar goal to yours with the suite of small TS utils:

![image](https://github.com/mesqueeb/is-what/assets/61068799/4e1c8636-a7da-4de2-b4d3-4028c613f6d2)

I think that mentioning them in the readme could be a good idea! 😊

**Comment by mesqueeb** [comment]
Not sure I see the value of me mentioning tinylibs : P

unless they wanna mention is-what and my other utils in return. But those marketing politics I don't have time for with OSS tbh. 😅  no disrespect!
