### ISSUE TITLE
GitHub Pages site doesn't exist

### ISSUE THREAD

**Issue by jcbhmr** [mesqueeb/is-what#51]
![image](https://github.com/mesqueeb/is-what/assets/61068799/ce16c447-efcc-41dd-832f-c2934fe3658d)

**Comment by mesqueeb** [comment]
: / I need to look into this!

**Comment by jcbhmr** [comment]
OHHH I know why. I forgot to let you know that you should _disable the environment requirement that you have to deploy from main_: 

![image](https://github.com/mesqueeb/is-what/assets/61068799/e9c263b7-e4ea-4e74-b679-fe12f7f09897)

This is the default setting:
![image](https://github.com/mesqueeb/is-what/assets/61068799/f86dd211-d8da-4764-bfe5-0a4f2f85f4a4)

It works well for things like this:
![image](https://github.com/mesqueeb/is-what/assets/61068799/77fbbd3e-b296-48cb-b893-6454cb8c6068)

BUT when you create a release and run the deploy-pages with a TAG as the base instead of MAIN, then it fails (and rightly so! That's what it was told to do 🤣)

So what you need to do is in https://github.com/mesqueeb/is-what/settings/environments, click on github-pages
![image](https://github.com/mesqueeb/is-what/assets/61068799/af13dbaf-5566-4d55-a86b-35482b4178ec)

and then drink in the config screen:
![image](https://github.com/mesqueeb/is-what/assets/61068799/aea2c1f4-00de-4c0e-ba87-1078188e8170)

and then either a) remove the protection altogether or b) reconfigure it so that it allows tags. IMO the simplest is to remove the protection which is the default for all other environments. The "github-pages" environment is one of (if not the only) special environment that when created gets special defaults! All others default to _absolutely zero_ restrictions. For instance, if you change:

https://github.com/mesqueeb/is-what/blob/27ce21e708b88414217975e3e7df9aa7e14a0469/.github/workflows/publish.yml#L25

to:

```yml
name: github-pages-hello
```

then it will work with no problem! How silly is that! 🤣

**Comment by mesqueeb** [comment]
@jcbhmr cool i deleted the environment

**Comment by jcbhmr** [comment]
It works!
![Uploading image.png…]()
