### ISSUE TITLE
Consider publishing solely to npm, and recommending Deno use npm:is-what?

### ISSUE THREAD

**Issue by jcbhmr** [mesqueeb/is-what#53]
![image](https://github.com/mesqueeb/is-what/assets/61068799/20c31ee1-bd2c-4934-b477-aab0bed9696e)
https://www.infoworld.com/article/3680389/deno-stabilizes-npm-compatibility.html

Would this be a viable option? With Deno introducing `npm:` specifiers last year, I don't know if it's necessary to keep two package publications alive.

@mesqueeb What's the current process for deploying? Do you manually run `npm publish`? What happens? How do you deploy to deno.land?

Cool tooling:
https://www.denoify.land/
https://github.com/denoland/publish-folder
https://docs.denoify.land/publishing-on-deno.land-x

**Comment by mesqueeb** [comment]
IIRC: Deno is linked to this repo: http://deno.land/x/is_what
and it uses the dist folder as the source code I think?

I don't personally use Deno, so I don't really care what happens to it. But I've received no complaints so far, so I think it just works...? 

Not sure I see the benefit in changing deno related things now.

> What's the current process for deploying? Do you manually run npm publish? What happens? How do you deploy to deno.land?

I run `npm run release` which uses [np](https://github.com/sindresorhus/np) it does a couple things for me at once.

further tooling can be discussed in https://github.com/mesqueeb/is-what/issues/40

**Comment by jcbhmr** [comment]
> IIRC: Deno is linked to this repo: http://deno.land/x/is_what
> and it uses the dist folder as the source code I think?

Probably? I don't know. You can check the Webhook under the Settings tab to see what the config is. It'd be good to document how the publishing works! 😊

Here's the page where you add your gh repo to the https://deno.land/x index: https://deno.com/add_module It's all down to a webhook!

> Not sure I see the benefit in changing deno related things now.

Benefit would just be a reduction in complexity. When you deploy to two places, now you need extra build tooling (possibly), extra consideration of testing to test both areas, extra CI to test both those things, extra management to actually _deploy_ to those places, etc.

If you drop the https://deno.land/x/is_what in favor of npm:is-what, now you only need to worry about how it get published to npm instead of a) how it gets published to npm and b) how it gets published to https://deno.land/x

> I run npm run release which uses [np](https://github.com/sindresorhus/np) it does a couple things for me at once.

You're saying you do this _manually_??? 😱 _\*incredulous!\*_ 😆
